nelmio_api_doc:
    documentation:
        info:
            title: Dochelper API
            description: API documentation for the Dochelper appointment platform.
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
